language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied

   # Install the lowest possible required version for the dependencies
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - export OLD_CPANM_OPT=$PERL_CPANM_OPT
   - export PERL_CPANM_OPT='--mirror http://cpan.metacpan.org/ --mirror http://search.cpan.org/CPAN '$PERL_CPANM_OPT
   - cpanm --verbose MSCHILLI/App-Daemon-0.01.tar.gz
   - cpanm --verbose SARTAK/Class-Load-0.01.tar.gz
   - cpanm --verbose TLINDEN/Config-General-2.38.tar.gz
   - cpanm --verbose GAAS/Data-Dump-1.10.tar.gz
   - cpanm --verbose RJBS/Email-Abstract-3.000.tar.gz
   - cpanm --verbose RJBS/Email-Sender-0.001.tar.gz
   - cpanm --verbose RJBS/Email-Simple-2.004.tar.gz
   - cpanm --verbose URI/File-Slurp-9999.14.tar.gz
   - cpanm --verbose DROLSKY/List-AllUtils-0.01.tar.gz
   - cpanm --verbose MSCHILLI/Log-Log4perl-1.15.tar.gz
   - cpanm --verbose MARKOV/Mail-IMAPClient-3.03.tar.gz
   - cpanm --verbose MSTROUT/Module-Metadata-1.000000.tar.gz
   - cpanm --verbose MSTROUT/Moo-1.000000.tar.gz
   - cpanm --verbose MATEU/MooX-Types-MooseLike-0.15.tar.gz
   - cpanm --verbose DTOWN/Net-SNMP-v6.0.0.tar.gz
   - cpanm --verbose VINSWORLD/Net-SNMPTrapd-0.01.tar.gz
   - cpanm --verbose LHOWARD/Net-Syslog-0.04.tar.gz
   - cpanm --verbose VINSWORLD/Net-Syslogd-0.01.tar.gz
   - cpanm --verbose KWILLIAMS/Path-Class-0.17.tar.gz
   - cpanm --verbose EVO/String-Escape-2010.002.tar.gz
   - cpanm --verbose ABW/Template-Toolkit-2.24.tar.gz
   - cpanm --verbose PHAYLON/namespace-clean-0.06.tar.gz
   - cpanm --verbose BBYRD/sanity-0.94.tar.gz
   - cpanm --verbose SAPER/Devel-SimpleTrace-0.07.tar.gz
   - cpanm --verbose INGY/JSONY-0.0.1.tar.gz
   - cpanm --verbose LHOWARD/Net-Syslog-0.04.tar.gz
   - cpanm --verbose LEONT/Test-CheckDeps-0.002.tar.gz
   - cpanm --verbose OVID/Test-Most-0.01.tar.gz
   - cpanm --verbose ISHIGAKI/Test-UseAllModules-0.10.tar.gz
   - export PERL_CPANM_OPT=$OLD_CPANM_OPT
script:
   - dzil smoke --release --author
notifications:
   email: false
